version: 2

jobs:
  macos:
    macos:
      xcode: "11.0.0"
    environment:
      - BAZEL_STARTUP_ARGS: "--output_base /Users/distiller/.cache/bazel"
      - BAZEL_BUILD_ARGS: "--local_ram_resources=12288 --local_cpu_resources=8 --verbose_failures --test_env=ENVOY_IP_TEST_VERSIONS=v4only --test_output=all -c opt"
      - BAZEL_ENVOY_PATH: "/Users/distiller/project/bazel-bin/src/envoy/envoy"
      - CC: clang
      - CXX: clang++
    steps:
      - run: sudo sntp -sS time.apple.com
      - run: brew tap bazelbuild/tap
      - run: brew install bazelbuild/tap/bazelisk cmake coreutils go libtool ninja wget
      - checkout
      - restore_cache:
          keys:
            - macos_fastbuild-bazel-cache-{{ checksum "WORKSPACE" }}-{{ checksum ".bazelrc" }}
      - run: rm ~/.gitconfig
      - run: make build_envoy
      - run: make test
      - save_cache:
          key: macos_fastbuild-bazel-cache-{{ checksum "WORKSPACE" }}-{{ checksum ".bazelrc" }}
          paths:
            - /Users/distiller/.cache/bazel
            - /Users/distiller/Library/Caches/bazelisk/

workflows:
  version: 2
  all:
    jobs:
      - macos
